#! /bin/bash

source /usr/lib/naylib

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

draw_heading "Install packages"

pkg up
uur upgrade

for pkg in `cat "$DIR/../packages" | sed -e '/^[ \t]*#/d' | sed '/^$/d'` ; do
  sudo -v
  uur native "$pkg" "Installing"
done

pip list 2> /dev/null | grep tasklib &> /dev/null || pip install tasklib
pip list 2> /dev/null | grep pynvim &> /dev/null || pip install pynvim 
